### ISSUE TITLE
Is the gen_server necessary?

### ISSUE THREAD

**Issue by markmeeus** [chaione/azure_push_client#3]
Hi,

First of all, thanks for publishing this library.

I was wondering why you implemented AzurePushClient.Message as a gen_server.
I think like this it could become a potential bottleneck because it can only send 1 push at a time.

grtz,
Mark

**Comment by rlb3** [comment]
Hello @markmeeus,

I used this this project to learn OTP and that's the main it's how it's written. In the project I'm using it in I have a Task supervisor that queues up outgoing messages.

```elixir
defp push_notification(payload, tags, format) do
    Enum.each tags, fn tag ->
        Task.Supervisor.start_child(Push.Supervisor, fn ->
            Azure.find_by_tag(tag) |> Message.send(payload, [tag], format)
        end)
    end
end
```

Let me know if this is any help.

rlb3

**Comment by rlb3** [comment]
For version 1.0 I decided to remove the GenServer

**Comment by markmeeus** [comment]
Nice!
